apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Repos\clc3-project\application_microservices\kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: user
status:
  loadBalancer: {}
