apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Repos\clc3-project\application_microservices\kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Repos\clc3-project\application_microservices\kompose-windows-amd64.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/application-microservices-default: "true"
        io.kompose.service: user
    spec:
      containers:
        - image: mathaler/user:latest
          name: user-api
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
