apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Repos\clc3-project\application_microservices\kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: movie
  name: movie
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: movie
status:
  loadBalancer: {}
