apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Repos\clc3-project\application_microservices\kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web-application
  name: web-application
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: web-application
status:
  loadBalancer: {}
