version: '3.9'

services:
  web-application:
    container_name: web-app
    image: mathaler/web:latest
    build:
      dockerfile: ./DockerfileWeb
    ports:
      - "8501:8501"
    depends_on:
      - movie
      - user

  movie:
    container_name: movie
    image: mathaler/movie:latest
    build:
      dockerfile: ./DockerfileMovie
    ports:
      - "5001:5001"
    depends_on:
      - database

  user:
    container_name: user
    image: mathaler/user:latest
    build:
      dockerfile: ./DockerfileUser
    ports:
      - "5002:5002"
    depends_on:
      - database

  database:
    container_name: database
    image: mathaler/db:latest
    build:
      context: ../../db
      dockerfile: ./DockerfileDB
    ports:
      - "5432:5432"
